### ISSUE TITLE
xvc file send error (S3)

### ISSUE THREAD

**Issue by OmerTrc** [iesahin/xvc#188]
Hi,

I tried to send my files to S3 but got the following error:

**Full backtrace:**

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', file/src/send.rs:72:34
stack backtrace:
   0:        0x103726302 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd2e8cbde22b780fc
   1:        0x1037484fa - core::fmt::write::hd6692086cdd356a7
   2:        0x10371e6bc - std::io::Write::write_fmt::h6043124a2486acbb
   3:        0x103727c5b - std::panicking::default_hook::{{closure}}::h87a12b8b06887dd7
   4:        0x103727967 - std::panicking::default_hook::h7f68dad17e0bfaa4
   5:        0x10372827f - std::panicking::rust_panic_with_hook::hd57427cbbfc3717a
   6:        0x103728182 - std::panicking::begin_panic_handler::{{closure}}::h33aab6d04e2bba70
   7:        0x103726798 - std::sys_common::backtrace::__rust_end_short_backtrace::h0e7a76f927db9964
   8:        0x103727e8d - _rust_begin_unwind
   9:        0x10377d193 - core::panicking::panic_fmt::hcf6f3c517c6f3cb3
  10:        0x10377d077 - core::panicking::panic::h46977cf6deabee02
  11:        0x103164a83 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h3ae85f760bd22e23
  12:        0x1031cf9cb - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hb4f07769796b97ee
  13:        0x103169a52 - xvc_file::send::cmd_send::h71b8f1414f8bdc26
  14:        0x103184e87 - xvc_file::run::h6f27c3454c6ddc25
  15:        0x102ff6786 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h86d8253b795cae5f
  16:        0x102fd3323 - std::sys_common::backtrace::__rust_begin_short_backtrace::h07d3b68a3599eace
  17:        0x102fc7d3c - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8b20dc35e1a5fb59
  18:        0x10372e1b7 - std::sys::unix::thread::Thread::new::thread_start::haa45038b11bc331d
  19:     0x7fff203768fc - __pthread_start
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', lib/src/cli/mod.rs:273:6
stack backtrace:
   0:        0x103726302 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd2e8cbde22b780fc
   1:        0x1037484fa - core::fmt::write::hd6692086cdd356a7
   2:        0x10371e6bc - std::io::Write::write_fmt::h6043124a2486acbb
   3:        0x103727c5b - std::panicking::default_hook::{{closure}}::h87a12b8b06887dd7
   4:        0x103727967 - std::panicking::default_hook::h7f68dad17e0bfaa4
   5:        0x10372827f - std::panicking::rust_panic_with_hook::hd57427cbbfc3717a
   6:        0x1037281c3 - std::panicking::begin_panic_handler::{{closure}}::h33aab6d04e2bba70
   7:        0x103726798 - std::sys_common::backtrace::__rust_end_short_backtrace::h0e7a76f927db9964
   8:        0x103727e8d - _rust_begin_unwind
   9:        0x10377d193 - core::panicking::panic_fmt::hcf6f3c517c6f3cb3
  10:        0x10377d2f5 - core::result::unwrap_failed::ha988429942445917
  11:        0x102fbe283 - xvc::cli::dispatch::h6cb0b458cd3e5b16
  12:        0x102f75284 - xvc::main::h02643c3fbc259b82
  13:        0x102f7518b - std::sys_common::backtrace::__rust_begin_short_backtrace::h6b49ecb8fbe72698
  14:        0x102f751b8 - std::rt::lang_start::{{closure}}::h76c1ee7dd2921ad7
  15:        0x10371890e - std::rt::lang_start_internal::ha5deaf08dab8765b
  16:        0x102f752cf - _main

**Comment by iesahin** [comment]
Thank you for reporting this. 

Did you add any files with `xvc file track` before send?

If so, could you run with `xvc -vvv file send`?

Not reporting a useful error message is certainly a bug.

**Comment by OmerTrc** [comment]
Hi,

Yes, i did track my files before send.

The result of `xvc -vvv file send`:

![result](https://user-images.githubusercontent.com/110227175/206650233-97cfb233-bd4e-4e00-9681-24b5a7766dec.png)

**Comment by iesahin** [comment]
I've added an error message and some tracepoints. 

Could you update with:

```
cargo install --git https://github.com/iesahin/xvc xvc
```

and let me know the trace of

```
xvc -vvvv file send 
```

Thanks.

**Comment by OmerTrc** [comment]
Hi,

I updated xvc with `cargo` and `xvc file send` command run without error message but there was no data file on S3 except .xvc-guid.

My Folder:

<img width="807" alt="folder" src="https://user-images.githubusercontent.com/110227175/206693726-febd5215-dbd0-4010-9e41-757cedb2a0dd.png">


Thx.

**Comment by iesahin** [comment]
It looks like a cache problem. That file is produced with `xvc storage new s3` command. 

What's the output of 

```
ls -R .xvc/
```

in your repository?

**Comment by OmerTrc** [comment]
Hi, 

The output of `ls -R .xvc/`: 

[xvc_output.txt](https://github.com/iesahin/xvc/files/10205301/xvc_output.txt)

Thx.

**Comment by iesahin** [comment]
The cache looks ok. 

Now, your workflow seems to be similar to: 

```console
$ git init
$ xvc init
$ xvc file track data.txt
$ xvc storage new s3 --name mystorage ...
$ xvc file send --to mystorage # without any paths.
```

Are there any other things that you did? Other commands, etc?

I'll write a test for this case to find the bug. 

One thing you can try is to supply a path to `xvc file send`, like `xvc file send --to mystorage myfile.txt`.  It should work. We have tests for this case, but not for calling the command without explicit targets. I'll add this test. 

Thanks.

**Comment by iesahin** [comment]
`xvc -vvvv file send` may be a bit noisy, but that could help me greatly to identify the problem. If you don't want to post the file here, you can send it to `contact@emresahin.net`.

**Comment by OmerTrc** [comment]
Hi, 

I updated `xvc file track data-folder/data` command to `xvc file track data-folder/data/images/*` and the problem was solved.

Thx.
